global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: '/metrics'
  - job_name: 'ot-initial-service'
    static_configs:
      - targets: ['ot-initial-service:8080']
    metrics_path: '/q/metrics'
  - job_name: 'ot-second-service'
    static_configs:
      - targets: ['ot-second-service:8081']
    metrics_path: '/q/metrics'
  - job_name: 'ot-third-service'
    static_configs:
      - targets: ['ot-third-service:8082']
    metrics_path: '/q/metrics'